// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Superjonikai.DB;

namespace Superjonikai.DB.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Superjonikai.Model.Entities.Bouquet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Bouquets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "yellow",
                            Name = "Simply gorgeous bouquet",
                            Price = 60.299999999999997
                        },
                        new
                        {
                            Id = 2,
                            Color = "yellow",
                            Name = "Summer flowers bouquet",
                            Price = 40.299999999999997
                        },
                        new
                        {
                            Id = 3,
                            Color = "yellow",
                            Name = "Mixed flowers",
                            Price = 16.399999999999999
                        },
                        new
                        {
                            Id = 4,
                            Color = "yellow",
                            Name = "Roses box",
                            Price = 12.0
                        },
                        new
                        {
                            Id = 5,
                            Color = "yellow",
                            Name = "Bright flower bouquet",
                            Price = 10.0
                        });
                });

            modelBuilder.Entity("Superjonikai.Model.Entities.Flower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Flowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "yellow",
                            Name = "Tulips",
                            Price = 0.69999999999999996
                        },
                        new
                        {
                            Id = 2,
                            Color = "yellow",
                            Name = "Roses",
                            Price = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Color = "yellow",
                            Name = "Lilies",
                            Price = 3.5
                        },
                        new
                        {
                            Id = 4,
                            Color = "yellow",
                            Name = "Sunflower",
                            Price = 7.5
                        });
                });

            modelBuilder.Entity("Superjonikai.Model.Entities.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Logins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kazkoks",
                            Password = "1234"
                        });
                });

            modelBuilder.Entity("Superjonikai.Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "gg",
                            FirstName = "a",
                            LastName = "b"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
